### ISSUE TITLE
feat: server room listing (stats)

### ISSUE THREAD

**Issue by hytracer** [WiiLink24/wfc-server#10]

**Comment by christiannemiralrama** [comment]
![Image](https://github.com/WiiLink24/wfc-server/assets/36115924/b0089c66-2b3d-4af3-b2d8-c548e5e490f7)

Introducing my first three sponsored Miis for Various Rooms: Navy, Yuzumi, and Dr. Kia. Let's start with Yuzumi.

Yuzumi
Room: Yuzumi Shintani (新谷ゆづみの間)
Videos:
- Yuzumi Reads a Touching Message from a Foreign Fan (eng subtitles) // SAKURA GAKUIN さくら学院
- Yuzumi Shintani (新谷ゆづみ) Cute and Funny Moments (Parts 1 and 2)
- Sara Yuzu TAKE
- Yuzumi's Birthday Surprise Messages - Yuzumi Shintani SHOWROOM 08/23/2023 - Shintani Yuzumi, Kawaii Moment (Special the Ciao Smiles)
- 元さくら学院・新⾕ゆづみ&⽇髙⿇鈴、圧巻の歌声を披露！複雑な心情を見事に演じる姿は必見 映画『麻希のいる世界』 (English as: Former Sakura Gakuin, Yuzumi Shintani & Marin Hidaka, show off their stunning singing voices! The appearance of brilliantly acting complex emotions is a must-see movie "The World with Maki")

Dr. Kia
Room: Kindness (親切の間) (Also a room for World Kindness Day)
Videos:
- Elmo and Carly Talk About Kindness
- My Little Pony: Friendship is Magic - Meet Fluttershy
- My Little Pony Equestria Girls Music Video - Good Vibes
Shopping gifts:
- Kindness bracelet
- Kindness wristband
- Kindness notebook
- Kindness stickers

Navy
Room: World War (世界大戦の間)
Videos:
- World War I
- World War II
- World War History
- Michael Jackson - Heal the World
- Terry Kelly - Pittance of Time (Remembrance Day Special)
- Mulan - Fighting Scenes
and more World War clips, including Marvel
Shopping gifts:
- Poppy
- Army badge

For the Christmas Room (クリスマスの間): I'll include a snow globe, glass ornament, nutcracker, and pumpkin pie as shopping gifts, and for the TALKLOID Room (トークロイドの間), there needs to be all former videos from Japan showing with subtitles.

The Japanese version will have translated titles, and Navy's clothes will be navy blue.

**Comment by hytracer** [comment]
@Humanoidear what format are you looking for on REST api request please
cc @mkwcat
