### ISSUE TITLE
Only one friend receives final auth message

### ISSUE THREAD

**Issue by mkwcat** [WiiLink24/wfc-server#2]
Applies to Mario Kart Wii
It seems when two players add each other, only the side that added the friend second seems to receive some kind of finalization, requiring the other player to log out and log back in to see the friend. This seems to specifically affect the game in that it won't attempt to search for the other player's friend info record in SAKE, but if the two players end up in a match together then it would work fine from there.
This _could_ be a client side issue, but I'm not sure

**Comment by mkwcat** [comment]
Fixed with 6f70dd1bafa64a30239d35ad4ee9ce4b325efe89

**Comment by hytracer** [comment]
yee good job :3
