### ISSUE TITLE
Importing DB doesnt work on PSQL

### ISSUE THREAD

**Issue by randomyaps** [WiiLink24/wfc-server#52]
Here's the logs:
postgres@randomyaps:~$ psql -U postgres wfc < /home/random/wfc-server/schema.sql
SET
SET
SET
SET
SET
 set_config 

 
(1 row)

SET
SET
SET
SET
SET
SET
CREATE TABLE
ERROR:  syntax error at or near "ALTER"
LINE 11: ALTER TABLE public.users OWNER TO wiilink;
         ^
CREATE SEQUENCE
ALTER TABLE
ERROR:  sequence must have same owner as table it is linked to
ALTER TABLE
ERROR:  relation "users_profile_id_seq" does not exist
ALTER TABLE

I still dont know.

**Comment by expiteRz** [comment]
`;` is missing at the end in line 50

**Comment by randomyaps** [comment]
I Will try that, Thanks!

**Comment by randomyaps** [comment]
> `;` is missing at the end in line 50

SET
SET
SET
SET
SET
 set_config
------------

(1 fila)

SET
SET
SET
SET
SET
SET
CREATE TABLE
ALTER TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
ALTER TABLE
psql:schema.sql:86: ERROR:  no existe la relaciÃ³n Â«users_profile_id_seqÂ»
ALTER TABLE

**Comment by randomyaps** [comment]
Doesnt work.

**Comment by expiteRz** [comment]
replace `users_profile_id_seq` with `public.users_profile_id_seq` in line 86
it should work

**Comment by randomyaps** [comment]
Worked! Thank you!
