### ISSUE TITLE
how do i get unbanned

### ISSUE THREAD

**Issue by SpareEnderboy** [WiiLink24/wfc-server#68]
i want to submit a ban appeal because i was banned from the wiilink discord

**Comment by AyeItsHarry** [comment]
First of all, this isn’t an issue with the WiiLink WFC server, so you should close this issue.
The ban appeal link is [this](https://tripetto.app/run/KWV4V3HPKH), which you also received in a DM when you got banned. If you do appeal, it is unlikely to be accepted due to how recent your ban is.

**Comment by Gemdation** [comment]
> i want to submit a ban appeal because i was banned from the wiilink discord

i wonder what was the thought process
